[package]
name = "channelmux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3.0"
futures = "0.3.30"
indexmap = "2.2.6"
